### ISSUE TITLE
Feature: User can view statistics for selected city

### ISSUE THREAD

**Issue by AnthonyVNgo** [AnthonyVNgo/ajax-project#2]
## ⚙️ Feature
Users will have the capability to view quality of life statistics of the searched city

## 📐 Functionality
After the user begins their search for a city on the main / search page, an alternative view with the city's quality of life score will appear. At this stage, the user will be able to review the stats for the searched city

## 🖼️ Wireframes
<img width="366" alt="image" src="https://user-images.githubusercontent.com/99709530/164114316-d1df402d-cb86-44d5-a269-54012544a804.png">

<img width="364" alt="image" src="https://user-images.githubusercontent.com/99709530/164114333-f0dcf6da-2acd-4dd4-b29e-8735a6874308.png">

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/99709530/164114527-908cc9f8-1294-4d55-957d-2345cbeffd78.png">

## ✅ Task List

- [x] display searched city name
- [x] create a list to showcase relevant statistics
- [x] include overall score for the city
