### ISSUE TITLE
Feature: User can store cities into Favorite or Skip lists

### ISSUE THREAD

**Issue by AnthonyVNgo** [AnthonyVNgo/ajax-project#3]
## ⚙️ Feature
User can store cities as favorited or skipped cities by clicking on the corresponding buttons

## 📐 Functionality
After the user has began the search and reviewed the city scores, they will be able to store the cities to reference later as a favorited or skipped city

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/99709530/165645018-85b4abed-a217-42d5-9f29-fcd7a69d7f23.png)

![image](https://user-images.githubusercontent.com/99709530/165644762-9d3e4d87-cb55-479e-ab53-4b7d077f1f3b.png)

## ✅ Task List
- [x] create favorite and skip buttons
- [x] add event handlers to the favorite and skip buttons to store data
- [x] add event handlers to return to the search page
