### ISSUE TITLE
Feature: User can view stored favorited or skipped cities as a list

### ISSUE THREAD

**Issue by AnthonyVNgo** [AnthonyVNgo/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="359" alt="image" src="https://user-images.githubusercontent.com/99709530/164117106-cd174d1f-ac66-4fc3-ac72-c0d9442ddfef.png">

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/99709530/164117061-c33f6b61-8420-40c8-a47a-ede887e95172.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] create alternate view to display a list of favorited & skipped cities
- [x] set up data model to contain favorited or skipped city
- [x] ensure no duplicated data can be added
- [x] ensure that city is in only one category 
- [x] populate favorited & skipped cities display
- [x] set up local storage to ensure favorites and skips data persists
