### ISSUE TITLE
Feature: User can remove items stored from the favorited or skipped cities list

### ISSUE THREAD

**Issue by AnthonyVNgo** [AnthonyVNgo/ajax-project#5]
## ⚙️ Feature
Users will have the capability to remove items from their favorited or skipped cities lists

## 📐 Functionality
After the user has made their search, reviewed city scores, and stored cities in either favorited or skipped lists, they will be able to remove unwanted cities from their corresponding lists by double-tapping on the list item

## 🖼️ Wireframes
<img width="368" alt="image" src="https://user-images.githubusercontent.com/99709530/164117567-78df4b52-a582-4837-9766-029915a69b23.png">

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/99709530/164117497-4668c51c-0e2c-4be0-bdc3-109af17bf84a.png">

## ✅ Task List
- [x] add an event handler to the list items' parent container to remove the corresponding items
- [x] make sure the data is also removed from the data storage object if any

**Clean Up**
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
